# default values for a local server
# docker run -it --name spire --rm -d -p 27015:27015 -p 27015:27015/udp -p 27025:27025 spiretf/docker-spire-server
rcon:
  host: 127.0.0.1:27015
  password: rcon

http:
  port: 6969
  read-timeout: 45s
  write-timeout: 45s
  idle-timeout: 45s

server:
  password: password

logger:
  level: info
  report-timestamp: true